### ISSUE TITLE
Details about model weights

### ISSUE THREAD

**Issue by rheaanan** [RonyAbecidan/ManTraNet-pytorch#7] opened 2022-02-19 03:36 UTC
The authors have published .h5 file weights in the original paper. How did you convert the .h5 file to .pt? i.e how did you convert the weights trained by Keras code to pytorch?

**Comment by RonyAbecidan** [comment] 2022-02-19 08:34
Hello, it's not straightforward to convert the .h5 file to .pt. What I have done is the following :

- I tried to reproduce step by step the architecture of MantraNet following the paper and the code released by the authors
- I inspected meticulously the weights of each layer of the MantraNet released in tensorflow and plugged them in my architecture
- I changed the architecture many times so that plugging these weights enabled me to reproduce exactly the same MantraNet that the one released by the authors
- At the end, when I finally converged to the good architecture, I saved the weights in '.pt'

So you see this is not just a conversion but rather a real work. Anyway having a kind of conversion of weights is not sufficient because you also need to "convert" the architecture from tf to pt.

**Closed** 2022-02-22 07:13 UTC
